spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
#    logic-delete-value: 1
#    logic-not-delete-value: 0
  global-config:
    db-config:
      id-type: auto
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss




server:
  port: 9000
#logging:
#  level:
#    com.atguigu.gulimall: debug

