spring:
  cloud:
    gateway:
      routes:
        # product_route 过滤器  路由规则更精确的放在最前边
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # member_route 过滤器
        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        # ware_route 过滤器
        - id: ware_route
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        #示例 可以n个 规则
        # renren-fast 过滤器
        - id: admin_route
          uri: lb://renren-fast   #lb负载均衡 路由给这个微服务
          predicates:
            - Path=/api/**        #前端项目有api
          filters:                #路径重写
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

#http://localhost:19999/api/captcha.jpg  规则转换http://renren-fast/api/captcha.jpg  404




