spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.151:8848
    alicloud:
      access-key: LTAI4GL2XJ5VFiV5qA5GG9qD
      secret-key: jlJp32NPwJPuhvzDgwa5dhnAqVMubC
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: gulimall-carlos

  application:
    name: gulimall-third-party

server:
  port: 30000
